main: main.o practica3.hpp practica5.hpp practica6.hpp tad_texto.hpp tad_tren.hpp tad_texto.hpp
	g++ main.cpp practica3.hpp practica5.hpp practica6.hpp tad_texto.hpp tad_tren.hpp tad_texto.hpp -o main -lm
	./main
